Repository HubSpot/Singularity, pull requests merged in 2020-07, with the labels that each got.

#2107 Only keep the most recent 50 failure events
  SingularityBase/src/main/java/com/hubspot/singularity/SingularityDeployStatisticsBuilder.java
  SingularityService/src/main/java/com/hubspot/singularity/scheduler/SingularityScheduler.java
Labels: hs_qa, hs_stable, hs_staging

#2108 Track shutdown time in status message
  SingularityExecutor/src/main/java/com/hubspot/singularity/executor/SingularityExecutorMonitor.java
  SingularityExecutor/src/main/java/com/hubspot/singularity/executor/task/SingularityExecutorTask.java
Labels: hs_qa, hs_stable, hs_staging

#2109 Wire up a `size` override for logrotateAdditionalFiles
  SingularityExecutor/src/main/java/com/hubspot/singularity/executor/TemplateManager.java
  SingularityExecutor/src/main/java/com/hubspot/singularity/executor/config/SingularityExecutorLogrotateAdditionalFile.java
  SingularityExecutor/src/main/java/com/hubspot/singularity/executor/config/SingularityExecutorModule.java
  SingularityExecutor/src/main/java/com/hubspot/singularity/executor/models/LogrotateAdditionalFile.java
  SingularityExecutor/src/main/java/com/hubspot/singularity/executor/models/LogrotateCronTemplateContext.java
  SingularityExecutor/src/main/java/com/hubspot/singularity/executor/models/LogrotateTemplateContext.java
  SingularityExecutor/src/main/java/com/hubspot/singularity/executor/task/SingularityExecutorTaskLogManager.java
  SingularityExecutor/src/main/resources/logrotate.cron.hbs
  SingularityExecutor/src/main/resources/logrotate.hourly.conf.hbs
  SingularityExecutor/src/main/resources/logrotate.sizebased.conf.hbs
  SingularityExecutor/src/test/java/com/hubspot/singularity/executor/config/SingularityExecutorConfigurationTest.java
Labels: hs_qa, hs_stable, hs_staging

#2113 More complete info level logging on offers
  SingularityService/src/main/java/com/hubspot/singularity/mesos/SingularityMesosOfferScheduler.java
Labels: hs_qa, hs_stable, hs_staging

#2116 Add warning about override and lb updates
  SingularityUI/app/components/common/modalButtons/KillTaskModal.jsx
Labels: hs_qa, hs_stable, hs_staging

#2117 Filter getRequestHistory queries by createdAt times
  SingularityBase/src/main/java/com/hubspot/singularity/SingularityRequestHistoryQuery.java
  SingularityClient/src/main/java/com/hubspot/singularity/client/SingularityClient.java
  SingularityService/src/main/java/com/hubspot/singularity/data/history/AbstractHistoryJDBI.java
  SingularityService/src/main/java/com/hubspot/singularity/data/history/HistoryJDBI.java
  SingularityService/src/main/java/com/hubspot/singularity/data/history/HistoryManager.java
  SingularityService/src/main/java/com/hubspot/singularity/data/history/JDBIHistoryManager.java
  SingularityService/src/main/java/com/hubspot/singularity/data/history/MySQLHistoryJDBI.java
  SingularityService/src/main/java/com/hubspot/singularity/data/history/NoopHistoryManager.java
  SingularityService/src/main/java/com/hubspot/singularity/data/history/PostgresHistoryJDBI.java
  SingularityService/src/main/java/com/hubspot/singularity/data/history/RequestHistoryHelper.java
  SingularityService/src/main/java/com/hubspot/singularity/resources/HistoryResource.java
  SingularityService/src/test/java/com/hubspot/singularity/SingularityHistoryTest.java
  SingularityService/src/test/java/com/hubspot/singularity/data/BlendedHistoryTest.java
Labels: hs_qa, hs_stable, hs_staging

#2105 Force index for task history requests by host and start/update times
  SingularityService/src/main/java/com/hubspot/singularity/data/history/AbstractHistoryJDBI.java
  SingularityService/src/main/java/com/hubspot/singularity/data/history/MySQLHistoryJDBI.java
  SingularityService/src/main/java/com/hubspot/singularity/data/history/PostgresHistoryJDBI.java
Labels: hs_qa, hs_staging

#2115 Bump mesos version to 1.9.0
  SingularityExecutor/Dockerfile
  SingularityExecutor/pom.xml
  SingularityServiceIntegrationTests/pom.xml
  compose-dev.yml
  docker-mesos/mesos-agent/Dockerfile
  docker-mesos/mesos-master/Dockerfile
  docker-mesos/mesos/Dockerfile
  pom.xml
Labels: staging
